source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'active_flag'
gem 'activerecord-import'
gem 'addressable'
gem 'algoliasearch-rails'
gem 'ancestry'
gem 'apollo_upload_server'
gem 'attr_encrypted', '~> 3.1.0'
gem 'aws-sdk-s3', '~> 1'
gem 'bcrypt'
gem 'blurhash'
gem 'bootsnap'
gem 'chewy'
gem 'connection_pool'
gem 'counter_culture'
gem 'doorkeeper', '~> 5.4.0'
gem 'doorkeeper-grants_assertion', github: 'doorkeeper-gem/doorkeeper-grants_assertion'
gem 'faraday'
gem 'faraday_middleware'
gem 'fast_blank'
gem 'fastimage'
gem 'flipper'
gem 'flipper-redis'
gem 'flipper-ui'
gem 'friendly_id'
gem 'google-api-client'
gem 'graphql'
gem 'graphql-batch'
gem 'graphql-client'
gem 'graphql-fancy_loader'
gem 'health_bit'
gem 'hiredis'
gem 'html-pipeline'
gem 'http'
gem 'i18n', '1.8.11'
gem 'ice_cube'
gem 'image_optim', require: false
gem 'image_optim_pack', require: false
gem 'image_processing'
gem 'iso-639'
gem 'iso_country_codes'
gem 'jsonapi-resources', '0.9.12'
gem 'jwt'
gem 'kramdown'
gem 'kramdown-parser-gfm'
gem 'marcel'
gem 'marginalia'
gem 'mechanize'
gem 'mini_magick'
gem 'mongo'
gem 'nokogiri'
gem 'oj'
gem 'oj_mimic_json'
gem 'one_signal'
gem 'opentelemetry-exporter-otlp'
gem 'opentelemetry-instrumentation-action_pack'
gem 'opentelemetry-instrumentation-active_record'
gem 'opentelemetry-instrumentation-faraday'
gem 'opentelemetry-instrumentation-graphql'
gem 'opentelemetry-instrumentation-mongo'
gem 'opentelemetry-instrumentation-rack'
gem 'opentelemetry-instrumentation-rails'
gem 'opentelemetry-instrumentation-redis'
gem 'opentelemetry-sdk'
gem 'parallel'
gem 'paranoia', '~> 2.4'
gem 'pg'
gem 'pghero'
gem 'pg_query'
gem 'postmark-rails'
gem 'prometheus_exporter'
gem 'puma'
gem 'pundit'
gem 'pundit-resources', github: 'hummingbird-me/pundit-resources'
gem 'rack-attack'
gem 'rack-cors'
gem 'rails', '6.1.6.1'
gem 'rails_admin', github: 'railsadminteam/rails_admin'
gem 'ranked-model'
gem 'redis', '> 3.3.0', require: ['redis', 'redis/connection/hiredis']
gem 'retriable'
gem 'rinku'
gem 'roadie-rails'
gem 'rolify'
gem 'ruby-progressbar'
gem 'sanitize'
gem 'scenic'
gem 'sentry-raven'
gem 'shrine'
gem 'shrine-blurhash'
gem 'sidekiq', '~> 5'
gem 'sidekiq-debounce'
gem 'sidekiq-scheduler'
gem 'sinatra'
gem 'sitemap_generator'
gem 'strait'
gem 'stream_rails', github: 'GetStream/stream-rails', branch: 'feature/subreference-enrichment'
gem 'stream-ruby', '~> 2.10.0'
gem 'stripe'
gem 'typhoeus'
gem 'vite_rails', '~> 3.0', '>= 3.0.13'

group :development, :test do
  gem 'benchmark-ips'
  gem 'database_cleaner'
  gem 'dead_end'
  gem 'derailed_benchmarks'
  gem 'dotenv-rails'
  gem 'factory_bot_rails'
  gem 'guard'
  gem 'guard-rspec', require: false
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rails-annotate-solargraph', '~> 0.5.4'
  gem 'rspec-rails'
  gem 'rubocop', require: false
  gem 'rubocop-graphql', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'solargraph', require: false
  gem 'spring'
end

group :test do
  gem 'faker'
  gem 'json_expressions'
  gem 'oauth2'
  gem 'rspec-sidekiq'
  gem 'shoulda-matchers'
  gem 'simplecov'
  gem 'stripe-ruby-mock', require: 'stripe_mock'
  gem 'timecop'
  gem 'webmock'
end

group :production, :staging do
  gem 'puma_worker_killer'
end
